[package]
name = "moonshine-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
goblin.workspace = true
dirs.workspace = true
thiserror.workspace = true
tracing.workspace = true
walkdir.workspace = true
uuid.workspace = true
chrono.workspace = true
tar.workspace = true
flate2.workspace = true
zip.workspace = true
