import Foundation

// MARK: - RustVec+MutableAccess
//
// swift-bridge's RustVec conforms to Collection, but its Sequence iterator yields
// T.SelfRef (read-only RustPrefixRef), not T.SelfRefMut (writable RustPrefixRefMut).
//
// This extension adds a public getMut(index:) that calls the static vecOfSelfGetMut
// already generated by swift-bridge for every Vectorizable type, giving us
// mutable element access without touching generated files.

extension RustVec {
    /// Returns a mutable reference to the element at the given index,
    /// or nil if the index is out of bounds.
    public func getMut(index: UInt) -> T.SelfRefMut? {
        T.vecOfSelfGetMut(vecPtr: ptr, index: index)
    }
}
